services:

  db:
    image: mariadb:latest
    container_name: lab1
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: lab1_adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: lab1
    ports:
      - "80:8080"
