#file: noinspection GrazieInspection,SpellCheckingInspection
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres-data:
