services:

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 10s
      start_interval: 5s
      interval: 3s
      timeout: 1s
      retries: 100

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    logging:
      driver: 'none'
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy

  app:
    image: pbd2_python
    container_name: python-app
    build:
      context: .
    volumes:
      - ./main.py:/python/main.py:r
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
